name: build
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        java: [ 21 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    if: |
      !contains(github.event.head_commit.message, '[no ci]')
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Get the mod version from gradle.properties
        id: get_version
        run: |
          MOD_VERSION=$(grep '^mod_version=' gradle.properties | cut -d'=' -f2)
          echo "MOD_VERSION=$MOD_VERSION" >> $GITHUB_ENV

      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Release to GitHub
        uses: gradle/gradle-build-action@v2
        with:
          arguments: chiseledBuildAndCollect

      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '21' }}
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: |
            build/libs/*.jar
            !build/libs/*-dev.jar
            !build/libs/*-sources.jar

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: "[Certain Questing Additions 1.20.1 - 1.21.1 | Latest Release]"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "latest"
          removeArtifacts: true
          allowUpdates: true
          artifacts: "build/libs/*.jar"
          artifactContentType: application/java-archive